In [50]:
import pandas as pd

In [51]:
df=pd.read_csv("IMDB Dataset.csv")

In [52]:
df.shape

(50000, 2)

In [53]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [54]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [55]:
df.drop_duplicates(inplace=True)

In [56]:
df.shape

(49582, 2)

# Text preprocessing

In [57]:
#converting to lowercase
df["review"]=df["review"].str.lower()
df.head(1)

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive

In [58]:
#removing url

import re  #regular expression

## sample="abc is the , abc"
## re.sub("abc","xyz",sample)

In [60]:
def remove_urls(text):
    text = re.sub(r"http\S+" , "", text)  # (pattern, repl, string) eg - https://www.google.com
    return text
    
df["review"] = df["review"].apply(remove_urls)

## df["review"].head()

0    one of the other reviewers has mentioned that ...
1    a wonderful little production. <br /><br />the...
2    i thought this was a wonderful way to spend ti...
3    basically there's a family where a little boy ...
4    petter mattei's "love in the time of money" is...
Name: review, dtype: object

In [65]:
def remove_punctuations(text):
    text = re.sub(r"[^A-Za-z0-9\s]" , "", text) # A-Z a-z 0-9 \s
    return text

df["review"] = df["review"].apply(remove_punctuations)

In [66]:
#removing html

def remove_html(text):
    text = re.sub(r"<.*?>" , "", text)
    return text

df["review"] = df["review"].apply(remove_html)

In [67]:
df["review"].head()

0    one of the other reviewers has mentioned that ...
1    a wonderful little production br br the filmin...
2    i thought this was a wonderful way to spend ti...
3    basically theres a family where a little boy j...
4    petter matteis love in the time of money is a ...
Name: review, dtype: object

In [68]:
# remove stopword

import nltk

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\amank\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\amank\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\amank\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [69]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [70]:
## sample="dark but just a game"
## token=word_tokenize(sample)
## token

['dark', 'but', 'just', 'a', 'game']

In [73]:
def remove_stopwords(text):
    token=word_tokenize(text)
    stopword=stopwords.words("english")

    for word in token:
        if word in stopword:
            text=text.replace(word,"")
    return text

df["review"] = df["review"].apply(remove_stopwords)

In [74]:
df.head()

                                              review sentiment
0  e    revewers  nted   wtchg  1 oz epode ll  ho...  positive
1   wderful ltle producti br br  filming techniqu...  positive
2   thought ths   wderful wy  spend tme   o hot s...  positive
3  bsclly res  fmly   lttle boy jke thks res  zom...  negative
4  petter mtte love   time  mey   vully stunng fi...  positive

In [78]:
#stemming

from nltk.stem import PorterStemmer

def stemming(text):
    ps = PorterStemmer()
    stemmed_words = []

    tokens = word_tokenize(text)
    for token in tokens:
        stemmed_token = ps.stem(token)
        stemmed_words.append(stemmed_token)

    return " ".join(stemmed_words)

df["review"] = df["review"].apply(stemming)

In [79]:
df.head()

                                              review sentiment
0  e revew nted wtchg 1 oz epod ll hook y rght ex...  positive
1  wder ltle producti br br film techniqu unssum ...  positive
2  thought th wder wy spend tme o hot summer week...  positive
3  bsclli re fmli lttle boy jke thk re zomb close...  negative
4  petter mtte love time mey vulli stunng film wt...  positive

In [80]:
#Encoding

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["sentiment"] = le.fit_transform(df["sentiment"])

In [81]:
y=df["sentiment"]

In [82]:
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

In [83]:
#vectorization

from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(max_features=1000)

X = tf.fit_transform(df["review"])

In [85]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2905400 stored elements and shape (49582, 1000)>
  Coords	Values
  (0, 693)	0.08090569614745986
  (0, 987)	0.16821200343475542
  (0, 225)	0.1991585192671591
  (0, 448)	0.07261104702940953
  (0, 696)	0.14140373649732313
  (0, 251)	0.09039649675187553
  (0, 382)	0.0903019579438986
  (0, 35)	0.12598940481887264
  (0, 300)	0.10828096842581347
  (0, 846)	0.06160055164855909
  (0, 718)	0.04918616616097478
  (0, 926)	0.39310908443877673
  (0, 749)	0.06494784639529165
  (0, 931)	0.08621465598374574
  (0, 329)	0.05503873926458333
  (0, 759)	0.257260445033984
  (0, 303)	0.09010247615013049
  (0, 652)	0.09398051875208656
  (0, 191)	0.09941427365343784
  (0, 751)	0.08479147882837314
  (0, 909)	0.0623574626336258
  (0, 78)	0.08566950880135711
  (0, 351)	0.08297265509042374
  (0, 810)	0.09700303614581403
  (0, 289)	0.09420682326159983
  :	:
  (49581, 241)	0.132084674324336
  (49581, 859)	0.10399193227206469
  (49581, 546)	0.11411167549991602
  (49581, 517)	0.507682053284925
  (49581, 253)	0.23139043435464476
  (49581, 985)	0.08411057611007633
  (49581, 334)	0.06258443744043499
  (49581, 582)	0.08418873367869138
  (49581, 353)	0.07727259418895871
  (49581, 547)	0.10165297895712523
  (49581, 803)	0.10222788246600199
  (49581, 963)	0.12822218336113658
  (49581, 284)	0.2110651084704411
  (49581, 878)	0.11295092815667357
  (49581, 64)	0.13505585663352437
  (49581, 827)	0.13090635548541665
  (49581, 380)	0.11992089767123719
  (49581, 88)	0.10111756849554461
  (49581, 430)	0.11445772741227145
  (49581, 907)	0.13889177724671437
  (49581, 711)	0.1048287592212407
  (49581, 925)	0.14828898514377992
  (49581, 387)	0.15358648195172084
  (49581, 83)	0.1497920459351757
  (49581, 66)	0.15992492989594118

## Dataset and DataLoader

In [87]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42
)

In [89]:
X_train.shape

(39665, 1000)

In [91]:
X_test.shape

(9917, 1000)

In [95]:
import torch
from torch.utils.data import TensorDataset, DataLoader

In [100]:
print(type(X_train))
print(type(X_test))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

In [101]:
train_set = TensorDataset(
    torch.from_numpy(X_train).float(),
    torch.from_numpy(y_train.values).float()
)

test_set = TensorDataset(
    torch.from_numpy(X_test).float(),
    torch.from_numpy(y_test.values).float()
)

In [102]:
train_loader = DataLoader(train_set, shuffle=True, batch_size=64)
test_loader = DataLoader(test_set, shuffle=True, batch_size=64)