In [50]:
import pandas as pd

In [51]:
df=pd.read_csv("IMDB Dataset.csv")

In [52]:
df.shape

(50000, 2)

In [53]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [54]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [55]:
df.drop_duplicates(inplace=True)

In [56]:
df.shape

(49582, 2)

# Text preprocessing

In [57]:
#converting to lowercase
df["review"]=df["review"].str.lower()
df.head(1)

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive

In [58]:
#removing url

import re  #regular expression

## sample="abc is the , abc"
## re.sub("abc","xyz",sample)

In [60]:
def remove_urls(text):
    text = re.sub(r"http\S+" , "", text)  # (pattern, repl, string) eg - https://www.google.com
    return text
    
df["review"] = df["review"].apply(remove_urls)

## df["review"].head()

0    one of the other reviewers has mentioned that ...
1    a wonderful little production. <br /><br />the...
2    i thought this was a wonderful way to spend ti...
3    basically there's a family where a little boy ...
4    petter mattei's "love in the time of money" is...
Name: review, dtype: object

In [65]:
def remove_punctuations(text):
    text = re.sub(r"[^A-Za-z0-9\s]" , "", text) # A-Z a-z 0-9 \s
    return text

df["review"] = df["review"].apply(remove_punctuations)

In [66]:
#removing html

def remove_html(text):
    text = re.sub(r"<.*?>" , "", text)
    return text

df["review"] = df["review"].apply(remove_html)

In [67]:
df["review"].head()

0    one of the other reviewers has mentioned that ...
1    a wonderful little production br br the filmin...
2    i thought this was a wonderful way to spend ti...
3    basically theres a family where a little boy j...
4    petter matteis love in the time of money is a ...
Name: review, dtype: object

In [ ]:
# remove stopword